version : "3"
services:
  # nginx:
  #   ports:
  #    - "3000:80"
  node-app:
    build:
      context: .
      # args:
      #   - NODE_ENV=development
    ports:
      - 8505:3000
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - WDS_SOCKET_HOST=127.0.0.1 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    #   - NODE_ENV=development
    #   - MONGO_USER=godfrey
    #   - MONGO_PASSWORD=mypassword

    command: npm start